# Generated by Django 4.2.13 on 2026-05-30 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(default='ESV', max_length=20)),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.PositiveIntegerField()),
                ('verse_start', models.PositiveIntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('verses', models.ManyToManyField(blank=True, related_name='collections', to='studies.verse')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(blank=True, default='John 3:16', on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='studies.verse')),
            ],
            options={
                'ordering': ['-read_at'],
                'unique_together': {('user', 'verse')},
            },
        ),
    ]
