# Generated by Django 4.2.13 on 2026-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='translation',
            field=models.CharField(default='ESV', max_length=20),
        ),
    ]
