# Generated by Django 5.2.9 on 2026-06-01 02:05

from django.db import migrations


def backfill_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('studies', 'UserProfile')
    ProgressEntry = apps.get_model('studies', 'ProgressEntry')

    for user in User.objects.all():
        verses_read = ProgressEntry.objects.filter(user=user).count()
        UserProfile.objects.get_or_create(user=user, defaults={'verses_read': verses_read})


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_add_user_profile'),
    ]

    operations = [
        migrations.RunPython(backfill_profiles, migrations.RunPython.noop),
    ]
