# Generated by Django 5.2.9 on 2026-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_backfill_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='book_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
